### ISSUE TITLE
fix the playlist icons plsslslsl

### ISSUE THREAD

**Issue by Vringster** [yazninja/apple-cider-lite#9]
playlist icon having kinda sorta bad color 
![image](https://user-images.githubusercontent.com/78688659/159547831-ec45dab0-ac81-4b9d-8dfb-23305e1d1f4f.png)
yay

**Comment by KillerParticles** [comment]
![image](https://user-images.githubusercontent.com/93286201/159549567-3e9d02a7-f3f5-4cf0-acb2-7de822275743.png)
 Was just about to post the same thing lmao, you beat me to it xD

Looks fine on Light mode IIRC, so only a dark mode issue by the looks of it.

**Comment by yazninja** [comment]
yoo my bad, i think i didnt add a switch for dark mode lmaoooo
